modLoader="javafml"
loaderVersion="[1,)" #mandatory
license="MIT"
[[mods]]
modId="itemdespawntowhat" #mandatory
version="${mod_version}" #mandatory

displayName="Item Despawn to What" #mandatory

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
authors="github meteoritel"
description='''
Customize the transformation of item drops after they disappear through configuration files.
'''

[[dependencies.itemdespawntowhat]]
modId="neoforge"
type="required"
versionRange="[21.1.210,)"
ordering="NONE"
side="BOTH"

[[dependencies.itemdespawntowhat]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"


